-- Creación de Tablas 
CREATE TABLE CATEGORIA (
ID INTEGER PRIMARY KEY NOT NULL,
Nombre TEXT
);

CREATE TABLE SUCURSAL 
(ID INTEGER PRIMARY KEY NOT NULL,
Nombre TEXT,
Dirección TEXT
);

CREATE TABLE CLIENTE (
ID INTEGER PRIMARY KEY NOT NULL,
Nombre TEXT,
Telefono INTEGER
);

CREATE TABLE PRODUCTO (
ID INTEGER PRIMARY KEY NOT NULL,
Nombre TEXT,
Marca TEXT,
Categoria_id INTEGER,
Precio_initario NUMERIC,
FOREIGN KEY (Categoria_id) REFERENCES CATEGORIA (ID));

CREATE TABLE STOCK (
ID INTEGER PRIMARY KEY NOT NULL,
Sucursal_id INTEGER NOT NULL,
Producto_id INTEGER NOT NULL,
Cantidad INTEGER,
FOREIGN KEY (Sucursal_id) REFERENCES SUCURSAL (ID),
FOREIGN KEY (Producto_id) REFERENCES PRODUCTO (ID)
UNIQUE (Sucursal_id, Producto_id)
);

CREATE TABLE ORDEN
(ID INTEGER PRIMARY KEY NOT NULL,
Sucursal_id INTEGER,
Cliente_id INTEGER,
Fecha DATE,
Total NUMERIC,
FOREIGN KEY (Sucursal_id) REFERENCES SUCURSAL (ID),
FOREIGN KEY (Cliente_id) REFERENCES CLIENTE (ID));

CREATE TABLE ITEM (
ID INTEGER PRIMARY KEY NOT NULL,
Orden_id INTEGER,
Producto_id INTEGER,
Cantidad INTEGER,
Monto_venta NUMERIC,
FOREIGN KEY (Orden_id) REFERENCES ORDEN (ID),
FOREIGN KEY (Producto_id) REFERENCES PRODUCTO (ID));

